[package]
name = "octorust"
version = "0.1.0"
edition = "2018"

[dependencies]
reqwest = { version = "0.11.4", features = ["json", "blocking"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0"